name: Vite

on:
  push:
    branches: ['master']

jobs:
  Buildndeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        # with:
        #   submodules: true
        #   token: ${{ secrets.REPO_SCOPED_TOKEN }
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.REPO_SCOPED_TOKEN }}"
      # - name: Reconfigure git to use HTTP authentication
      #   run: >
      #     git config --global url."https://github.com/".insteadOf
      #     ssh://git@github.com/
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: setup git config
        run: |
          git config --global user.email "lahadn@gmail.com"
          git config --global user.name "Adnan Lahrech"
      - name: Running deploy.sh
        run: bash ./deploy.sh
